STANDARD_USER_ERROR = "Sorry, we're facing an unexpected issue on our end. Please try again later."

def get_user_error() -> str:
    return STANDARD_USER_ERROR